config/routes.rb
Rails.application.routes.draw do

  get 'logs/update'

  get 'overtimes/create'

  get '/signup', to: 'users#new'  #新規ユーザー登録
  
  get '/login', to: 'sessions#new'  #ログイン画面
  post '/login', to: 'sessions#create'  #ログイン画面
  delete '/logout', to: 'sessions#destroy' 
  root 'top_page#top'
  
  resources :bases
  
  
  resources :users do
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
      get 'index_working'
      resources :requests, only: [:create, :destroy]
      post 'create_request'
      get 'one_month_output'
      get 'approval_logs'
      patch 'logs'
    end
    resources :attendances, only: [:update]
    collection { post :import }
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :attendances, dependent: :destroy
  has_many :requests, dependent: :destroy
  has_many :logs, dependent: :destroy
  
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
    
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
              format: { with: VALID_EMAIL_REGEX },uniqueness: true
  validates :affiliation, length: { in: 2..30 }, allow_blank: true
  validates :basic_time, presence: true
  validates :work_time, presence: true
  validates :designated_work_start_time, presence: true
  validates :designated_work_end_time, presence: true
  
  
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  
  
  def User.digest(string)
    cost =
    if ActiveModel::SecurePassword.min_cost
      BCrypt::Engine::MIN_COST
    else
      BCrypt::Engine.cost
    end
    BCrypt::Password.create(string, cost: cost)
  end
  
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  def self.search(search) 
    if search
      where(['name LIKE ?', "%#{search}%"]) 
    else
      all
    end
  end
    
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      user = new
      user.attributes = row.to_hash.slice(*updatable_attributes)
      user.save!
    end
  end
    
  def self.updatable_attributes
    ["name", "email", "affiliation", "employee_number", "uid", "basic_time", 
    "designated_work_start_time", "designated_work_end_time", "superior", "admin", "password"]
  end
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :edit_basic_info, :update_basic_info, :one_month_output, :approval_logs, :logs, :superior_user?, :corect_user2]
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy, :edit_basic_info, :update_basic_info]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: [:destroy, :index, :import, :index_working]
  before_action :set_one_month, only: [:show, :one_month_output, :approval_logs]
  before_action :confirm_show, only: [:show]
  before_action :corect_user2, only: [:approval_logs]

  def index
    @users = User.paginate(page: params[:page], per_page: 5).search(params[:search]).order(:id)
  end

  def import
    User.import(params[:file])
    flash[:success] = "CSVファイルをインポートしました。"
    redirect_to users_url
  end

  def index_working
    @users = []
    User.all.each do |user|
      if user.attendances.any?{|a| ( Date.today && !a.started_at.blank? && a.finished_at.blank?)}
        @users.push(user)
      end
    end
  end
  
  def show
    redirect_to users_path if current_user.admin?
    if current_user?(@user) || current_user.requests.pluck(:applicant).include?(@user.id)
      @worked_sum = @attendances.where.not(started_at: nil).count
      @attendance1 = @user.attendances.find_by(worked_on: @first_day)
      @users = User.where(superior: "2")
      @request = Request.new
      @requests1 = @user.requests.where(category: 1).order(:applicant)
      @requests2 = @user.requests.where(category: 2).order(:applicant)
      @requests3 = @user.requests.where(category: 3).order(:applicant)
      @applied_users1 = @requests1.pluck(:applicant).uniq
      @applied_users2 = @requests2.pluck(:applicant).uniq
      @applied_users3 = @requests3.pluck(:applicant).uniq
    end
  end
  
  def one_month_output
    respond_to do |format|
      format.html do
          #html用の処理を書く
      end 
      format.csv do
          #csv用の処理を書く
      end
    end
  end
  
  def approval_logs
    @attendances_all = @user.attendances.where(status2: 2).order(:worked_on)
    @attendances = @attendances_all.where(worked_on: @first_day..@last_day)
  end
  
  def logs
    @date = Date.new( params["date(1i)"].to_i, params["date(2i)"].to_i)
    redirect_to approval_logs_user_url(@user, date: @date.beginning_of_month)
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = '新規作成に成功しました。'
      redirect_to @user
    else
      render :new
    end
  end

  def edit
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報を更新しました。"

      if current_user.admin?
        redirect_to users_url 
      else
        redirect_to @user
      end
    else
      render :edit      
    end
  end

  def destroy
    @user.destroy
    flash[:success] = "#{@user.name}のデータを削除しました。"
    redirect_to users_url
  end

  def edit_basic_info
  end

  def update_basic_info
    if @user.update_attributes(basic_info_params)
      flash[:success] ="#{@user.name}の基本情報を更新しました"
    else
      flash[:danger] = "#{@user.name}の更新は失敗しました。<br>" + @user.errors.full_messages.join("<br>")
    end
    redirect_to users_url
  end
  
  def search
    @users = User.search(params[:search])
  end
 
  
  private

    def user_params
      params.require(:user).permit(:name, :email, :affiliation, :password, :password_confirmation, :employee_number, :uid, :basic_time, :designated_work_start_time, :designated_work_end_time)
    end
    
    
    
    def basic_info_params
      params.require(:user).permit(:department, :work_time, :basic_time)
    end

    def logged_in_user
      unless logged_in?
         store_location
        flash[:danger] = "ログインしてください"
        redirect_to login_url
      end
    end
    
    # 正しいユーザーかどうか確認
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless (@user == current_user) || current_user.admin?
    end
    
    def corect_user2
      redirect_to(root_url) unless @user == current_user
    end
    
    def confirm_show
      redirect_to(root_url) unless current_user?(@user) || (params[:confirm] == Digest::MD5.hexdigest(@user.name))
    end
    
end

app/helpers/users_helper.rb
module UsersHelper
  
  def format_basic_info(time)
    format("%.2f",(time.hour*60 + time.min) / 60.00)
  end
  
  def a_user(id, date)
    User.find(id).attendances.find_by(worked_on: date)
  end
  
  def superior_user?
    @user.superior > 1
  end
  
end

app/views/users/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_with(model: @user, local: true) do |f| %>
    
      <%= render 'shared/error_messages', object: @user %>
      
      <%= f.label :name, class: "label-#{yield(:label_class)}" %>
      <%= f.text_field :name, class: "form-control" %>
      
      <%= f.label :email, class: "label-#{yield(:label_class)}" %>
      <%= f.email_field :email, class: "form-control" %>
      
      <%= f.label :affiliation, class: "label-#{yield(:label_class)}" %>
      <%= f.text_field :affiliation, class: "form-control" %>
      
      <%= f.label :password, class: "label-#{yield(:label_class)}" %>
      <%= f.password_field :password, class: "form-control" %>
      
      <%= f.label :password_confirmation, class: "label-#{yield(:label_class)}" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>
      
      <%= f.submit yield(:submit_class), class: "btn btn-primary btn-block btn-#{yield(:label_class)}" %>
    <% end %>

 </div>
</div>

app/views/users/approval_logs.html.erb
<h1>勤怠ログ(<%= @first_day.year %>年<%= @first_day.month %>月)</h1>


<%= form_with(url: logs_user_path, method: :patch, local: true) do |f| %>
<%= f.date_select :date , { discard_day: true,
                            start_year: Date.today.year,
                            end_year: @attendances_all.first.try(:worked_on).try(:year) } %>
<%= f.submit "更新", class: "btn btn-primary" %>
<% end %>

<% if @attendances.present? %>
  <table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th class="center">日付</th>
        <th class="center">変更前出社時間</th>
        <th class="center">変更前退社時間</th>
        <th class="center">変更後出社時間</th>
        <th class="center">変更後退社時間</th>
        <th class="center">指示者</th>
        <th class="center">承認</th>
      </tr>
    </thead>
    <tbody>
      <% @attendances.each do |a| %>
        <tr>
          <td><%= a.worked_on.try(:strftime, "%y/%m/%d") %></td>
          <td><%= a.first_started_at.try(:localtime).try(:strftime, "%H:%M") if a.first_started_at != a.started_at %></td>
          <td><%= a.first_finished_at.try(:localtime).try(:strftime, "%H:%M") if a.first_finished_at != a.finished_at %></td>
          <td><%= a.started_at.try(:strftime, "%H:%M") %></td>
          <td><%= a.finished_at.try(:strftime, "%H:%M") %></td>
          <td><%= User.find_by(id: a.superior).try(:name) %></td>
          <td><%= a.approval_date.try(:strftime, "%y/%m/%d") %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <% else %>
    <h3>勤怠の変更ログはありません。</h3>
    <h3>他の日付を選択してください。</h3>
  <% end %>

app/views/users/edit.html.erb
<% provide(:title, "ユーザー情報編集" ) %>
<% provide(:submit_class, "ユーザー情報更新") %>

<div class="container">
  <h1 class="center">ユーザー情報編集</h1>
  <%= render 'form' %>
</div>

app/views/users/edit_basic_info.html.erb
<% provide(:class_text, '基本情報編集') %>
<% provide(:button_text, '更新') %>


<!--<h1 class="modal-title">基本情報の更新</h1>-->
    
<!--<div class="row">-->
<!--  <div class="col-md-6 col-md-offset-3">-->
<!--    <%= form_with(model: @user,url: user_path, local: true, method: :patch) do |f| %>-->
<!--      <%= render 'shared/error_messages', object: @user %>-->

<!--      <%= f.label :name, class: "label-#{yield(:class_text)}" %>-->
<!--      <p><%= @user.name %></p>-->

<!--      <%= f.label :affiliation, "所属", class: "label-#{yield(:class_text)}" %>-->
<!--      <%= f.text_field :affiliation, class: "form-control" %>-->

<!--      <%= f.label :basic_time, class: "label-#{yield(:class_text)}" %>-->
<!--      <%= f.time_field :basic_time, class: "form-control" %>-->

<!--      <%= f.label :work_time, class: "label-#{yield(:class_text)}" %>-->
<!--      <%= f.time_field :work_time, class: "form-control" %>-->

<!--      <div class="center">-->
<!--        <%= f.submit yield(:button_text), class: "btn btn-primary btn-#{yield(:class_text)}" %>-->
<!--        <%= link_to "キャンセル", users_path, class: "btn btn-default" %>-->
<!--      </div>-->
<!--    <% end %>-->
<!--  </div>-->
<!--</div>-->

app/views/users/index.html.erb
<% provide(:title, "ユーザー一覧") %>

<div class="container">
  
  
<h1>
  <%= params[:search].nil? ? "ユーザ一覧" : "検索結果" %>
</h1>

<div class="name-search">
  <p>ユーザー検索</p>
  <%= form_tag( users_path, method: :get) do %>
    <%= text_field_tag :search %>
    <%= submit_tag '検索', name: nil %>
  <% end %>
</div>

<%= form_with(url: import_users_path, multipart: true) do |f| %>
  <%= f.file_field :file %>
  <%= f.submit "CSVをインポート", class: "btn btn-primary" %>
<% end %>

<%= will_paginate %>
<div class="container user-index">
  <% @users.each do |user| %>
    <p><%= user.name %></p>
    <% if !user.admin? %>
      <p><%= link_to "削除", user, data: { confirm: "削除してよろしいですか？"}, class: "btn btn-primary", method: :delete %></p>
    <% end %>
    <a class="btn btn-primary btn-lg" data-toggle="collapse" href="#collapse<%= user.id %>" 
      role="button" aria-expanded="false" aria-controls="collapse<% user.id %>">編集</a>
    <div class="collapse" id="collapse<%= user.id %>">
      <%= form_with model: user, url: user_path(user.id), method: :patch, local: true do |f| %>
        <%= f.label :name, class: "label-form" %>
        <%= f.text_field :name, class: "form-control" %>
        <%= f.label :email, class: "label-form" %>
        <%= f.email_field :email, class: "form-control" %>
        <%= f.label :affiliation, "所属", class: "label-form" %>
        <%= f.text_field :affiliation, class: "form-control" %>
        <%= f.label :employee_number, "社員番号", class: "label-form" %>
        <%= f.number_field :employee_number, class: "form-control" %>
        <%= f.label :uid, "カードID", class: "label-form" %>
        <%= f.text_field :uid, class: "form-control" %>
        <%= f.label :password, class: "label-form" %>
        <%= f.password_field :password, class: "form-control" %>
        <%= f.label :password_confirmation, class: "label-form" %>
        <%= f.password_field :password_confirmation, class: "form-control" %>
        <%= f.label :basic_time, class: "label-form" %>
        <%= f.time_field :basic_time, class: "form-control" %>
        <%= f.label :designated_work_start_time, "指定勤務開始時間", class: "label-form" %>
        <%= f.time_field :designated_work_start_time, class: "form-control" %>
        <%= f.label :designated_work_end_time, "指定勤務終了時間", class: "label_form" %>
        <%= f.time_field :designated_work_end_time, class: "form-control" %>
        <%= f.submit "編集内容を更新", class: "btn btn-primary btn-block" %>
      <% end %>
    </div>
  <% end %>
</div>
<%= will_paginate %>


</div>

app/views/users/index_working.html.erb
<% provide(:title, "出勤社員一覧") %>

<h1>出勤社員一覧</h1>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th class="center">社員番号</th>
      <th class="center">名前</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.employee_number %></td>
        <td><%= user.name %></td>
      </tr>
    <% end %>
  </tbody>
  
</table>

app/views/users/new.html.erb
<% provide(:title,"Sign-up") %>
<% provide(:submit_class, "新規登録") %>

<h1 class="center">アカウント作成</h1>
<%= render 'form' %>
  