config/routes.rb
Rails.application.routes.draw do

  get 'logs/update'

  get 'overtimes/create'

  get '/signup', to: 'users#new'  #新規ユーザー登録
  
  get '/login', to: 'sessions#new'  #ログイン画面
  post '/login', to: 'sessions#create'  #ログイン画面
  delete '/logout', to: 'sessions#destroy' 
  root 'top_page#top'
  
  resources :bases
  
  
  resources :users do
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
      get 'index_working'
      resources :requests, only: [:create, :destroy]
      post 'create_request'
      get 'one_month_output'
      get 'approval_logs'
      patch 'logs'
    end
    resources :attendances, only: [:update]
    collection { post :import }
  end
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user

  validates :worked_on, presence: true

  # 出勤時間が存在しない場合、退勤時間は無効
  validate :finished_at_is_invalid_without_a_started_at
  validate :started_at_and_finished_at


  def finished_at_is_invalid_without_a_started_at
    errors.add(:started_at, "が必要です") if started_at.blank? && finished_at.present?
  end
  
  def started_at_and_finished_at
    if started_at.present? && finished_at.present?
      errors.add(:started_at, "より早い時間は無効です") if (finished_at < started_at) && (change_date != 1)
    end
  end
  
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :set_user, only: :edit_one_month
  before_action :logged_in_user, only: [:update, :edit_one_month]
  before_action :set_one_month, only: :edit_one_month
  
UPDATE_ERROR_MSG = "勤怠登録に失敗しました。やり直してください。"

  def update
    @user = User.find(params[:user_id])
    @attendance = Attendance.find(params[:id])
    
    # 出勤時間が未登録であることを判定します。
    if @attendance.started_at.nil?
      if @attendance.update_attributes(started_at: DateTime.current.change(sec: 0).round_to(15.minutes))
        @attendance.update_attributes(first_started_at: DateTime.current.change(sec: 0).round_to(15.minutes))
        @user.update_attributes(working: 1)
        flash[:info] = "おはようございます！"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    elsif @attendance.finished_at.nil?
      if @attendance.update_attributes!(finished_at: DateTime.current.change(sec: 0).round_to(15.minutes))
        @attendance.update_attributes!(first_finished_at: DateTime.current.change(sec: 0).round_to(15.minutes))
        @user.update_attributes(working: 0)
        flash[:info] = "お疲れ様でした。"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    end
    redirect_to @user
  end
  
  def edit_one_month
    @users = User.where(superior: "2")
    @request = Request.new
  end
  
  def update_one_month
    ActiveRecord::Base.transaction do
      attendances_params.each do |id, item|
        attendance = Attendance.find(id)
        attendance.update_attributes!(item)
      end
    end
      flash[:success] = "更新に成功しました。"
      redirect_to user_url(date: params[:date])
    rescue ActiveRecord::RecordInvalid
      flash[:danger] = "無効な入力があったので、更新がキャンセルされました。"
      redirect_to attendances_edit_one_month_user_url(date: params[:date])
  end
  
  private
    
    def attendances_params
      params.require(:user).permit(attendances: [:started_at, :finished_at, :note])[:attendances]
    end
    
end

app/helpers/attendances_helper.rb
module AttendancesHelper
  
  def worked_time(start1, finish1, change_date)
    if change_date == 1
      format("%.2f", (finish1 - start1)/3600)
    elsif (((finish1.hour*60) + finish1.min - (start1.hour*60) - start1.min)/60) >= 0
      format("%.2f", (finish1.hour*60 + finish1.min - start1.hour*60 - start1.min)/60.00)
    else
      format("%.2f", ((finish1.hour*60) + finish1.min + (24*60) - (start1.hour*60) - start1.min)/60.00)
    end
  end
  
  def start_time(start)
    start = start.round_to(15.minutes)
  end
  
  def finish_time(finish)
    finish = finish.round_to(15.minutes)
  end 
 
end

app/views/attendances/edit_one_month.html.erb
<% provide(:title, "勤怠編集") %>

<h1>勤怠編集</h1>


<%= form_with(url: requests_path, local: true, method: :post) do |f| %>
<p>※出社・退社・備考・指示者は必ず入力してください。</p>
  <table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th class="center">日付</th>
        <th class="center">曜日</th>
        <th class="center">出社</th>
        <th class="center">退社</th>
        <th class="center">翌日</th>
        <th class="center">備考</th>
        <th class="center">指示者確認</th>
      </tr>
    </thead>
    <tbody>
      <% @attendances.each_with_index do |day, index| %>
        <%= f.fields_for @request do |r| %>
        <tr>
          <td><%= l(day.worked_on, format: :short) %></td>
          <td>
            <% if day.worked_on.wday == 0 %>
              <font color="red"><%= $week[day.worked_on.wday] %></font>
            <% elsif day.worked_on.wday == 6 %>
              <font color="blue"><%= $week[day.worked_on.wday] %></font>
            <% else %>
              <%= $week[day.worked_on.wday] %>
            <% end %>
          </td>
          
          <% if !current_user.admin? && (Date.current < day.worked_on) %>
              <td><%= f.time_select :started_at, {include_blank: true, disabled: true} %></td>
              <td><%= f.time_select :finished_at, {include_blank: true , disabled: true} %></td>
              <td><%= %></td>
              <td><%= f.text_field :note, disabled: true, class: 'form-control' %></td>
              <td></td>
            <% else %>  
              <td>
                <% if day.started_at.present? %>
                   <span><%= day.started_at.strftime("%-H:%M") %>　→　</span>
                <% end %>
                <%= f.time_select "started_at[#{index}]", {include_blank: true, minute_step: 15} %></td>
              <td>
                <% if day.finished_at.present? %>
                   <span><%= day.finished_at.strftime("%-H:%M") %>　→　</span>
                <% end %>
                <%= f.time_select "finished_at[#{index}]",{include_blank: true, minute_step: 15} %></td>
              <td><%= f.check_box "change_date[#{index}]"%></td>
              <td><%= f.text_field "note[#{index}]", class: 'form-control' %></td>
              <td><%= f.select "superior[#{index}]", @users.where.not(id: @user.id).pluck(:name), include_blank: true %></td>
              <%= f.hidden_field "request_date[#{index}]", value: day.worked_on %>
              <%= r.hidden_field :category, value: 2 %>
              <%= r.hidden_field :applicant, value: params[:id] %>
            <% end %>
        </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
  <div class="center">
    <%= f.submit "編集を登録", class: "btn btn-primary btn-lg" %>
    <%= link_to "キャンセル", user_path(date: @first_day), class: "btn btn-default btn-lg" %>
  </div>
<% end %>