config/routes.rb
Rails.application.routes.draw do

  get 'logs/update'

  get 'overtimes/create'

  get '/signup', to: 'users#new'  #新規ユーザー登録
  
  get '/login', to: 'sessions#new'  #ログイン画面
  post '/login', to: 'sessions#create'  #ログイン画面
  delete '/logout', to: 'sessions#destroy' 
  root 'top_page#top'
  
  resources :bases
  
  
  resources :users do
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
      get 'index_working'
      resources :requests, only: [:create, :destroy]
      post 'create_request'
      get 'one_month_output'
      get 'approval_logs'
      patch 'logs'
    end
    resources :attendances, only: [:update]
    collection { post :import }
  end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Attendance App", root_path, class: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "トップ", root_path %></li>
          <% if logged_in? %>
          <% if current_user.admin? %>
            <li><%= link_to "ユーザ一覧", users_path %></li>
            <li><%= link_to "出勤社員一覧", index_working_user_path(current_user) %></li>
            <li><%= link_to "拠点情報の修正", bases_path %></li>
            <li><%= link_to "基本情報の編集", edit_basic_info_user_path(current_user) %></li>
          <% end %>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">アカウント<b class="caret"></b></a>
              <ul class="dropdown-menu">
               
                  <li><%= link_to "勤怠", current_user if !current_user.admin? %></li>
               
                <li><%= link_to "設定", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li><%= link_to "ログアウト", logout_path, method: :delete %></li>
              </ul>
          </li>
        <% else %>
          <li><%= link_to "ログイン", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
  <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <% if !params[:confirm].present? %>
      <%= render 'layouts/header' %>
    <% end %>
    <div class="container">
      <% flash.each do |message_type, msg| %>
        <div class="alert alert-<%= message_type %>"><%= msg.html_safe %></div>
      <% end %>
   
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>